services:
  nest-server:
    build:
      target: build
    environment:
      - DATABASE_URL=postgresql://app:app@nest-postgres:5432/app?schema=public
    ports:
      # Port for debugging
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:debug

  postgres-db:
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
