services:
  abc-fos-server:
    container_name: abc-fos-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    environment:
      - SERVER_PORT=${SERVER_PORT:-3000}
    depends_on:
      - abc-fos-db

  abc-fos-db:
    container_name: abc-fos-db
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: ${VOLUME_NAME:-abc-fos-db-data}
